name: just_put
description: Just put and make a game.

publish_to: "none"

version: 0.4.0+10

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.18
  webview_flutter: ^4.0.6
  path_provider: ^2.0.13
  permission_handler: ^10.2.0
  file_picker: ^5.2.6
  image_picker: ^0.8.7
  google_mobile_ads: ^2.4.0
  flutter_slidable: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/www/html_editor.html
    - assets/www/css/style.css
    - assets/www/js/sortable.js
    - assets/www/js/render_list.js
    - assets/www/js/btn_element.js
    - assets/www/js/start_scene.js
    - assets/www/js/save_data.js
    - assets/www/js/file_pieces_scene.js
    - assets/www/js/texture_code.js
    - assets/www/js/pieces_code.js
    - assets/www/js/edit_params.js
    - assets/www/js/data_creator.js
    - assets/www/js/html_spawner.js

  fonts:
    - family: Cuprum
      fonts:
        - asset: assets/www/fonts/Cuprum-Bold.woff2
          weight: 700
        - asset: assets/www/fonts/Cuprum-Bold-Cirillic.woff2
          weight: 700
        - asset: assets/www/fonts/Cuprum-Regular.ttf
          style: normal
